form_settings:
  taxonomy_term:
    default_value: false
    disable: false
    hidden: false
  block_content:
    default_value: false
    disable: false
    hidden: false
  comment:
    default_value: false
    disable: false
    hidden: false
  contact_message:
    default_value: false
    disable: false
    hidden: false
  file:
    default_value: false
    disable: false
    hidden: false
  node:
    default_value: false
    disable: false
    hidden: false
  shortcut:
    default_value: false
    disable: false
    hidden: false
  user:
    default_value: false
    disable: false
    hidden: false
  menu_link_content:
    default_value: false
    disable: false
    hidden: false
  commerce_product_attribute_value:
    default_value: false
    disable: false
    hidden: false
  commerce_product_variation:
    default_value: false
    disable: false
    hidden: false
  commerce_product:
    default_value: false
    disable: false
    hidden: false
  commerce_store:
    default_value: false
    disable: false
    hidden: false
  mirtek_product:
    default_value: false
    disable: false
    hidden: false
  mirtek_product_group:
    default_value: false
    disable: false
    hidden: false
  path_alias:
    default_value: false
    disable: false
    hidden: false
  paragraph:
    default_value: false
    disable: false
    hidden: false
no_suffix: false
take_ownership: false
