features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 1
telephone: '8 800 250 33 88'
footer_email: infotd@mirtekgroup.ru
footer_telephone: '+7 8652 99 12 10'
telegram: 'https://t.me/mirtek_group'
rutube: 'https://rutube.ru/channel/25019158/'
vk: 'https://vk.com/mirtekgroup'
