cloneable_entities:
  - block
  - block_content
  - block_content_type
  - comment_type
  - comment
  - commerce_currency
  - commerce_product_attribute
  - commerce_product_attribute_value
  - commerce_product_variation
  - commerce_product_type
  - commerce_product
  - commerce_product_variation_type
  - commerce_store
  - commerce_store_type
  - contact_message
  - contact_form
  - editor
  - field_config
  - field_storage_config
  - file
  - filter_format
  - image_style
  - configurable_language
  - language_content_settings
  - menu_link_content
  - mirtek_product
  - mirtek_product_group_type
  - mirtek_product_type
  - node_type
  - node
  - path_alias
  - search_page
  - shortcut_set
  - shortcut
  - menu
  - action
  - taxonomy_term
  - taxonomy_vocabulary
  - ultimate_cron_job
  - user
  - user_role
  - view_mode_page_pattern
  - pathauto_pattern
  - view
  - paragraphs_type
  - paragraph
  - date_format
  - base_field_override
  - entity_view_mode
  - entity_form_display
  - entity_form_mode
  - entity_view_display
  - swiper_formatter
  - cookie_category
  - webform
  - webform_options
  - webform_submission
  - search_api_index
  - search_api_server
  - search_api_task
  - search_api_synonym
  - solr_field_type
  - solr_request_handler
  - solr_request_dispatcher
  - solr_cache
