version: '3.9'

services:
  drupal-webserver:
    image:          nginx:latest
    depends_on:     [ drupal ]
    volumes_from:   [ drupal:rw ]
    ports:          [ 127.0.78.1:4588:80 ]
    volumes:        [ ./config/webserver:/etc/nginx/conf.d:ro ]
    command:        [ nginx-debug, '-g', 'daemon off;' ]

  drupal-database:
    image:          "mysql:8.0.16"
    command:        ["--max_allowed_packet=67108864", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=Europe/Berlin
    volumes:
      - ./var/database:/var/lib/mysql
      - ./var/db-dump:/docker-entrypoint-initdb.d

  drupal:
    image:          registry.mirtek.git:5050/web/sites/corporate-website:prod
    depends_on:     [ drupal-database ]
    # build:
    #   context: .
    env_file:
      - .env
    environment:
      DB_DSN: "mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:3306/${DB_NAME}"
      HASH_SALT: 43d6aOjLe/onM5vv0PBDBw==
    volumes:
#      - ./config/php/php.dev.ini:/usr/local/etc/php/php.ini

      # Project files
      - ./.env:/app/.env
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock

      # Drupal config files
      - ./web/sites:/app/web/sites

      - ./config/drupal:/app/config/drupal
      - ./web/themes/custom:/app/web/themes/custom
      - ./web/modules/custom:/app/web/modules/custom
      - ./web/libraries:/app/web/libraries

#  phpmyadmin:
#      image:          phpmyadmin/phpmyadmin:latest
#      ports:          [ 127.0.1.99:80:80 ]
#      depends_on:     [ drupal-database ]
#      environment:    [ PMA_ARBITRARY=1, PMA_HOST=drupal-database ]
