<?php

/**
 * @file
 * Helper module for Twig typography tests.
 */

/**
 * Implements hook_theme().
 */
function twig_typography_test_theme($existing, $type, $theme, $path) {
  return [
    'twig_typography_test_filter' => [
      'variables' => [
        'message_first' => NULL,
        'message_second' => NULL,
        'message_third' => NULL,
      ],
      'template' => 'twig_typography_test.filter',
    ],
  ];
}
