custom:
  text_current: '{current} из {total}'
  text_previous: '« Предыдущий'
  text_next: 'Следующий »'
  text_close: Закрыть
  initialwidth: '300'
  slideshow:
    text_start: 'запустить слайдшоу'
    text_stop: 'остановить слайдшоу'
